const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const html = fs.readFileSync(path.join(__dirname, 'spain-portugal-2026.html'), 'utf8');
const script = html.split('<script>')[1]?.split('</script>')[0];
if (!script) throw new Error('Inline app script missing');
new vm.Script(script);
const match = script.match(/const D = ([\s\S]*?);\r?\n/);
if (!match) throw new Error('Data payload missing');
const d = JSON.parse(match[1]);
const assert = (condition, message) => { if (!condition) throw new Error(message); console.log('PASS', message); };
const key = s => String(s || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
const guide = d.sanSebastianGuide;
const names = new Set(d.pois.map(p => key(p.name)));
const find = date => d.days.find(day => day.date === date);

assert(!html.includes('/*__DATA__*/'), 'generated payload present');
assert(d.itinerary.length === 8 && d.days.length === 18, 'trip itinerary retained');
assert(d.pois.length === 123 && d.restaurants.length === 63, 'new restaurant pins and entries present');
assert(d.pois.every(p => Number.isFinite(p.lat) && Number.isFinite(p.lon)), 'all pins have coordinates');
assert(d.restaurants.every(r => names.has(key(r.Restaurant))), 'restaurant rows resolve to map pins');
assert(d.sights.every(r => names.has(key(r['Site / Activity']))), 'sight rows resolve to map pins');
assert(d.reservations.every(r => names.has(key(r['Restaurant / Booking']))), 'reservation rows resolve to map pins');
assert(new Set(guide.map(v => key(v.name))).size === guide.length, 'guide venues are unique');
assert(guide.every(v => v.source.startsWith('https://') && v.address && v.hours && v.price && v.booking && Number.isFinite(v.lat) && Number.isFinite(v.lon)), 'guide records have practical details and sources');
assert(guide.filter(v => v.bourdain).map(v => v.name).sort().join('|') === ['Asador Etxebarri','Casa Urola','Elkano','Ganbara'].sort().join('|'), 'Bourdain labels limited to documented venues');
assert(guide.some(v => v.name === 'Ganbara downstairs dining room' && v.groups.includes('Sit-down dinner')), 'Ganbara dining room separate from bar');
assert(['Near us in Gros','Pintxo crawl','Sit-down dinner','Optional outings'].every(g => guide.some(v => v.groups.includes(g))), 'all guide groups populated');
assert(find('2026-09-29').city === 'San Sebastian' && find('2026-10-04').city === 'San Sebastian' && find('2026-10-05').city === 'Madrid', 'San Sebastián stay and Monday departure dated correctly');
const birthday = d.reservations.find(r => key(r['Restaurant / Booking']) === key('Martín Berasategui'));
assert(birthday.Status === 'CONFIRMED' && birthday['Dining Date'] === '2026-10-02' && birthday.Time === '9:15 PM' && birthday.Party === 3, 'Friday birthday booking retained');
const etxebarri = d.reservations.find(r => key(r['Restaurant / Booking']) === key('Asador Etxebarri'));
assert(etxebarri.Status === 'WAITLIST' && !etxebarri['Dining Date'], 'Etxebarri waitlist has no invented date');
assert(!d.reservations.some(r => /Arzak/i.test(r['Restaurant / Booking'])), 'Arzak not represented as a reservation');
assert(!guide.some(v => /Arzak/i.test(v.name)), 'Arzak not recommended');
assert(!find('2026-09-29').events.some(e => /crawl/i.test(e.what)), 'proposed crawl not marked complete or booked');
assert(guide.every(v => v.city === 'San Sebastian'), 'outings remain discoverable from base city');
assert(guide.find(v => v.name === 'Elkano').area === 'Getaria' && guide.find(v => v.name === 'Gran Sol').area === 'Hondarribia', 'outings retain accurate town labels');
console.log('Verification passed.');
